const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('desktop', {
  getState: () => ipcRenderer.invoke('get-state'),
  openExternal: url => ipcRenderer.invoke('open-external', url),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  setMode: mode => ipcRenderer.send('set-mode', mode),
  positionOverlay: data => ipcRenderer.send('position-overlay', data),
  quickPositionSingle: data => ipcRenderer.send('quick-position-single', data),
  arrangeOverlays: layout => ipcRenderer.send('arrange-overlays', layout),
  openQuickPosition: () => ipcRenderer.send('open-quick-position'),
  openSettings: () => ipcRenderer.send('open-settings'),
  closeQuickPosition: () => ipcRenderer.send('close-quick-position'),
  setQuickPanelCollapsed: collapsed => ipcRenderer.send('set-quick-panel-collapsed', collapsed),
  saveQuickPanelState: data => ipcRenderer.send('save-quick-panel-state', data),
  setQuickPanelTop: enabled => ipcRenderer.send('set-quick-panel-top', enabled),
  saveSources: data => ipcRenderer.send('save-sources', data),
  saveOptions: data => ipcRenderer.send('save-options', data),
  saveHotkeys: data => ipcRenderer.invoke('save-hotkeys', data),
  overlayClick: index => ipcRenderer.send('overlay-click', index),
  dragStart: data => ipcRenderer.send('drag-start', data),
  moveOverlay: data => ipcRenderer.send('move-overlay', data),
  dragEnd: index => ipcRenderer.send('drag-end', index),
  resizeOverlay: data => ipcRenderer.send('resize-overlay', data),
  onSourceChanged: fn => ipcRenderer.on('source-changed', (_e, data) => fn(data)),
  onOptionsChanged: fn => ipcRenderer.on('options-changed', (_e, data) => fn(data)),
  onVisibilityChanged: fn => ipcRenderer.on('visibility-changed', (_e, visible) => fn(visible)),
  onStateChanged: fn => ipcRenderer.on('state-changed', (_e, data) => fn(data)),
  onUpdateCheckResult: fn => ipcRenderer.on('update-check-result', (_e, data) => fn(data))
});
